Repository KeYProject/key, pull requests merged in 2023-06, with the labels that each got.

#3128 AutoPerf: Lazy rule indices
  key.core.symbolic_execution/src/main/java/de/uka/ilkd/key/symbolic_execution/rule/ModalitySideProofRule.java
  key.core/src/main/java/de/uka/ilkd/key/java/declaration/VariableSpecification.java
  key.core/src/main/java/de/uka/ilkd/key/logic/Semisequent.java
  key.core/src/main/java/de/uka/ilkd/key/logic/Sequent.java
  key.core/src/main/java/de/uka/ilkd/key/proof/BuiltInRuleAppIndex.java
  key.core/src/main/java/de/uka/ilkd/key/proof/Goal.java
  key.core/src/main/java/de/uka/ilkd/key/proof/RuleAppIndex.java
  key.core/src/main/java/de/uka/ilkd/key/proof/TacletAppIndex.java
  key.core/src/main/java/de/uka/ilkd/key/proof/rulefilter/SetRuleFilter.java
  key.core/src/main/java/de/uka/ilkd/key/prover/impl/PerfScope.java
  key.core/src/main/java/de/uka/ilkd/key/strategy/QueueRuleApplicationManager.java
  key.core/src/main/java/de/uka/ilkd/key/strategy/RuleAppContainer.java
  key.core/src/test/resources/de/uka/ilkd/key/java/testAttachCommentsCompilationUnit_LockSpec.txt
  key.core/tacletProofs/seqPerm2/Taclet_schiffl_lemma_2.proof
  key.ui/examples/heap/permissions/lockspec/src/LockSpec.java
  key.ui/src/main/resources/logback.xml
Labels: Prover Core

#3154 Fix proof view filter not applied on load
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIProofTreeModel.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java
Labels: GUI

#3133 Fix NPE while extracting recoder error position and use existing information better
  key.core/src/main/java/de/uka/ilkd/key/java/Recoder2KeY.java
  key.core/src/test/java/de/uka/ilkd/key/speclang/njml/JMLParserExceptionTest.java
  key.core/src/test/resources/de/uka/ilkd/key/speclang/njml/exceptional/KeyTest.java
Labels: KeY Parser

#3166 fix StringUtil.trim
  key.util/src/main/java/org/key_project/util/java/StringUtil.java
  key.util/src/test/java/org/key_project/util/testcase/java/StringUtilTest.java
Labels: :lady_beetle: Bug

#3029 JUnit XML files for RunAllProofs
  .github/workflows/tests.yml
  gradle/wrapper/gradle-wrapper.properties
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/Function.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/JunitXmlWriter.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/RunAllProofsTest.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/RunAllProofsTestUnit.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/proofcollection/StatisticsFile.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/proofcollection/TestFile.java
Labels: Infrastructure

#3169 Update README.md
  README.md
Labels: Documentation

#3177 Reduce logging in slicing extension
  keyext.slicing/src/main/java/org/key_project/slicing/analysis/DependencyAnalyzer.java
  keyext.slicing/src/test/java/org/key_project/slicing/EndToEndTests.java
Labels: P:HIGH, keyext.slicing

#3173 Make assignable predicate available in JML
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/heap.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/heapRules.key
Labels: Feature

#3182 fixes #3092
  key.core/src/main/java/de/uka/ilkd/key/speclang/ContractFactory.java
Labels: Calculus
