Repository KeYProject/key, pull requests merged in 2023-12, with the labels that each got.

#3263 Handle bound variables in SMT unknown translation
  key.core/src/main/java/de/uka/ilkd/key/smt/newsmt2/MasterHandler.java
  key.core/src/main/java/de/uka/ilkd/key/smt/newsmt2/ModularSMTLib2Translator.java
  key.core/src/main/java/de/uka/ilkd/key/smt/newsmt2/QuantifierHandler.java
  key.core/src/main/java/de/uka/ilkd/key/smt/newsmt2/SMTHandler.java
  key.core/src/test/resources/de/uka/ilkd/key/smt/newsmt2/cases/unknownQuantified.props
Labels: SMT, Review Request

#3368 Fix update of proof tree in case of filter changes (fixes #3367)
  key.core/src/main/java/de/uka/ilkd/key/settings/ViewSettings.java
  key.ui/src/main/java/de/uka/ilkd/key/core/KeYSelectionModel.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/actions/HidePackagePrefixToggleAction.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/actions/PrettyPrintToggleAction.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/actions/SyntaxHighlightingToggleAction.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/actions/UnicodeToggleAction.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIBranchNode.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/GUIProofTreeModel.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreePopupFactory.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeSearchBar.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java
  key.ui/src/main/java/de/uka/ilkd/key/proof/io/ProblemLoader.java
Labels: :lady_beetle: Bug, Review Request

#3373 Configurable enabled keys for JML condition evaluation
  key.core/src/main/java/de/uka/ilkd/key/settings/GeneralSettings.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/njml/JmlMarkerDecision.java
Labels: Feature

#3370 Get rid of experimental flag using more fine-grained flags
  key.core/src/main/java/de/uka/ilkd/key/settings/AbstractPropertiesSettings.java
  key.core/src/main/java/de/uka/ilkd/key/settings/FeatureSettings.java
  key.core/src/main/java/de/uka/ilkd/key/settings/ProofIndependentSMTSettings.java
  key.core/src/main/java/de/uka/ilkd/key/settings/ProofIndependentSettings.java
  key.core/src/main/java/de/uka/ilkd/key/settings/ViewSettings.java
  key.ui/build.gradle
  key.ui/src/main/java/de/uka/ilkd/key/core/Main.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/MainWindow.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/ProofMacroMenu.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/colors/ColorSettings.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/colors/ColorSettingsProvider.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/extension/ExtensionManager.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/extension/impl/Extension.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/extension/impl/HeatmapExt.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/extension/impl/TestExtension.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/keyshortcuts/ShortcutSettings.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/CurrentGoalViewMenu.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/caching/CachingSettingsProvider.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreePopupFactory.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/settings/DefaultSettingsProvider.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/settings/FeatureSettingsPanel.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/settings/SettingsManager.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/settings/SettingsProvider.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/settings/SettingsUi.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/settings/StandardUISettings.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/settings/TacletOptionsSettings.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/NewTranslationOptions.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/SMTSettingsProvider.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/SolverOptions.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/TacletTranslationOptions.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/smt/settings/TranslationOptions.java
  keyext.slicing/src/main/java/org/key_project/slicing/SlicingSettingsProvider.java
  keyext.slicing/src/test/java/org/key_project/slicing/EndToEndTests.java
  keyext.ui.testgen/src/main/java/de/uka/ilkd/key/gui/testgen/TestgenOptionsPanel.java
Labels: Feature

#3161 ADTs for KeY
  .gitignore
  key.core/src/main/antlr4/KeYLexer.g4
  key.core/src/main/antlr4/KeYParser.g4
  key.core/src/main/antlr4/gen/KeYLexer.java
  key.core/src/main/java/de/uka/ilkd/key/nparser/KeyAst.java
  key.core/src/main/java/de/uka/ilkd/key/nparser/ParsingFacade.java
  key.core/src/main/java/de/uka/ilkd/key/nparser/builder/DeclarationBuilder.java
  key.core/src/main/java/de/uka/ilkd/key/nparser/builder/FunctionPredicateBuilder.java
  key.core/src/main/java/de/uka/ilkd/key/nparser/builder/TacletPBuilder.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/ProofCollections.java
  key.ui/examples/standard_key/adt/dt_color.key
  key.ui/examples/standard_key/adt/dt_color.proof
  key.ui/examples/standard_key/adt/dt_list_appnil.key
  key.ui/examples/standard_key/adt/dt_list_appnil.proof
  key.ui/examples/standard_key/adt/dt_list_revrev.key
  key.ui/examples/standard_key/adt/dt_list_revrev.proof
  key.ui/examples/standard_key/adt/dt_nat.key
  key.ui/examples/standard_key/adt/dt_nat.proof
  test/enum.key
  test/list.key
Labels: KeY Parser, Calculus, Review Request
