Repository KeYProject/key, pull requests merged in 2023-04, with the labels that each got.

#3096 JUnit XML files for optional-tests
  .github/workflows/tests.yml
Labels: CI, 🛠 Maintenance

#3098 Artiweb workflow fix
  .github/workflows/artiweb.yml
Labels: Deployment

#3106 A Github Action for nightly deploy
  .github/workflows/nightlydeploy.yml
Labels: Deployment, CI

#3110 Tests on Windows
  .github/workflows/tests.yml
  key.core/src/test/java/de/uka/ilkd/key/smt/newsmt2/MasterHandlerTest.java
  key.core/src/test/java/de/uka/ilkd/key/util/DesignTests.java
Labels: Deployment

#3109 Depromote optional-tests
  .github/workflows/opttest.yml
  .github/workflows/tests.yml
Labels: CI, 🛠 Maintenance

#3062 Floating Point rules for casts
  key.core/src/main/java/de/uka/ilkd/key/logic/sort/ProgramSVSort.java
  key.core/src/main/java/de/uka/ilkd/key/rule/conditions/FloatingPointBalancedCondition.java
  key.core/src/main/java/de/uka/ilkd/key/rule/conditions/TypeResolver.java
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/floatAssignment2UpdateRules.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/integerAssignment2UpdateRules.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/javaRules.key
  key.core/src/test/resources/de/uka/ilkd/key/nparser/taclets.old.txt
Labels: Calculus

#3121 fix typo in opttest
  .github/workflows/opttest.yml
Labels: :lady_beetle: Bug, CI

#3126 Fix source view line numbers font size
  key.ui/src/main/java/de/uka/ilkd/key/gui/sourceview/SourceView.java
Labels: GUI

#3129 Fix double highlight in sequent view
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/InnerNodeView.java
Labels: GUI
