Repository KeYProject/key, pull requests merged in 2023-02, with the labels that each got.

#3001 Install SMT solvers for CI testing
  .github/dlsmt.sh
  .github/workflows/tests.yml
Labels: P:HIGH, SMT, CI

#3004 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Infrastructure

#3008 Fix construction of Javac issue dialog
  key.core/src/main/java/de/uka/ilkd/key/java/Position.java
  key.core/src/main/java/de/uka/ilkd/key/proof/JavaModel.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/IssueDialog.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/PositionedIssueString.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/javac/JavaCompilerCheckFacade.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/javac/JavacExtension.java
  key.ui/src/test/java/de/uka/ilkd/key/gui/plugins/javac/JavaCompilerCheckFacadeTest.java
Labels: GUI

#3025 Report location on error in constant evaluation
  key.core/src/main/java/de/uka/ilkd/key/java/PosConvertException.java
  key.core/src/main/java/de/uka/ilkd/key/java/Recoder2KeY.java
  key.core/src/main/java/de/uka/ilkd/key/java/recoderext/ConstantStringExpressionEvaluator.java
  key.core/src/test/java/de/uka/ilkd/key/parser/TestParser.java
  key.core/src/test/resources/testcase/parserErrorTest/AssignToArray.java
  recoder/src/main/java/recoder/java/CompilationUnit.java
  recoder/src/main/java/recoder/java/NonTerminalProgramElement.java
Labels: Java Parser

#3016 Draft: Fix javacc deprecation warning
  key.core/build.gradle
  key.core/src/main/javacc/de/uka/ilkd/key/parser/proofjava/JavaCharStream.java
  key.core/src/main/javacc/de/uka/ilkd/key/parser/schemajava/JavaCharStream.java
Labels: 🛠 Maintenance

#3036 New .git-blame-ignore-revs after history rewrite
  .git-blame-ignore-revs
Labels: 🛠 Maintenance

#3037 Avoid tooltip NPE for incomplete proof nodes
  key.ui/src/main/java/de/uka/ilkd/key/gui/prooftree/ProofTreeView.java
Labels: :lady_beetle: Bug

#3010 Upload HTML test report
  .github/workflows/tests.yml
Labels: P:NORMAL, Feature, Infrastructure
