Repository KeYProject/key, pull requests merged in 2024-03, with the labels that each got.

#3424 added checkbox to disable example loader directly in dialog
  key.ui/src/main/java/de/uka/ilkd/key/gui/ExampleChooser.java
Labels: GUI, Feature, HacKeYthon

#3439 Fix startup crash if ~/.key/colors.json is not present
  key.core/src/main/java/de/uka/ilkd/key/nparser/ParsingFacade.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/colors/ColorSettings.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/colors/ColorSettingsProvider.java
Labels: Robustness

#3445 fix smt solver downloader script
  .github/dlsmt.sh
Labels: CI

#3444 Update broken link in README.md
  README.md
Labels: Documentation

#3400 Immutable and valid JML set statement
  key.core.symbolic_execution/src/main/java/de/uka/ilkd/key/symbolic_execution/rule/QuerySideProofRule.java
  key.core.symbolic_execution/src/main/java/de/uka/ilkd/key/symbolic_execution/strategy/breakpoint/AbstractConditionalBreakpoint.java
  key.core.symbolic_execution/src/test/resources/testcase/set/useOperationContractStatementsInImpliciteConstructor/oracle/UseOperationContractStatementsInImpliciteConstructor.xml
  key.core/src/main/antlr4/JmlParser.g4
  key.core/src/main/java/de/uka/ilkd/key/informationflow/proof/init/StateVars.java
  key.core/src/main/java/de/uka/ilkd/key/java/JavaTools.java
  key.core/src/main/java/de/uka/ilkd/key/java/KeYJavaASTFactory.java
  key.core/src/main/java/de/uka/ilkd/key/java/Recoder2KeYConverter.java
  key.core/src/main/java/de/uka/ilkd/key/java/recoderext/JMLTransformer.java
  key.core/src/main/java/de/uka/ilkd/key/java/recoderext/JmlAssert.java
  key.core/src/main/java/de/uka/ilkd/key/java/recoderext/SetStatement.java
  key.core/src/main/java/de/uka/ilkd/key/java/statement/JmlAssert.java
  key.core/src/main/java/de/uka/ilkd/key/java/statement/SetStatement.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/CreatingASTVisitor.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/JavaASTVisitor.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/ProgVarReplaceVisitor.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/ProgramVariableCollector.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/Visitor.java
  key.core/src/main/java/de/uka/ilkd/key/ldt/HeapLDT.java
  key.core/src/main/java/de/uka/ilkd/key/logic/op/LocationVariable.java
  key.core/src/main/java/de/uka/ilkd/key/nparser/KeyAst.java
  key.core/src/main/java/de/uka/ilkd/key/pp/LogicPrinter.java
  key.core/src/main/java/de/uka/ilkd/key/pp/PrettyPrinter.java
  key.core/src/main/java/de/uka/ilkd/key/pp/SequentViewLogicPrinter.java
  key.core/src/main/java/de/uka/ilkd/key/proof/SemisequentTacletAppIndex.java
  key.core/src/main/java/de/uka/ilkd/key/proof/init/JavaProfile.java
  key.core/src/main/java/de/uka/ilkd/key/proof/mgt/SpecificationRepository.java
  key.core/src/main/java/de/uka/ilkd/key/rule/JmlAssertRule.java
  key.core/src/main/java/de/uka/ilkd/key/rule/SetStatementBuiltInRuleApp.java
  key.core/src/main/java/de/uka/ilkd/key/rule/SetStatementRule.java
  key.core/src/main/java/de/uka/ilkd/key/rule/conditions/FieldTypeToSortCondition.java
  key.core/src/main/java/de/uka/ilkd/key/rule/conditions/StaticFieldCondition.java
  key.core/src/main/java/de/uka/ilkd/key/rule/metaconstruct/IntroAtPreDefsOp.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/SLEnvInput.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/jml/pretranslation/TextualJMLAssertStatement.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/jml/translation/JMLSpecFactory.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/njml/JmlIO.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/njml/PreParser.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/njml/TextualTranslator.java
  key.core/src/test/java/de/uka/ilkd/key/java/ProofJavaProgramFactoryTest.java
  key.core/src/test/java/de/uka/ilkd/key/logic/TestTermLabelManager.java
  key.core/src/test/java/de/uka/ilkd/key/parser/TestIntLiteralParsing.java
  key.core/src/test/java/de/uka/ilkd/key/parser/TestJMLParserAssociativity.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/ProofCollections.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/ProveTest.java
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/proofcollection/ProofCollection.java
  key.core/src/test/java/de/uka/ilkd/key/speclang/SetStatementTest.java
  key.core/src/test/java/de/uka/ilkd/key/speclang/jml/TestJMLTranslator.java
  key.core/src/test/java/de/uka/ilkd/key/speclang/jml/pretranslation/TextualJMLAssertStatementTest.java
  key.core/src/test/resources/testcase/setStatements/testFile.key
  key.core/src/test/resources/testcase/setStatements/testPackage/TestClass.java
  key.ui/examples/heap/list_seq/src/ArrayList.java
  key.ui/examples/heap/list_seq/src/LinkedList.java
  key.ui/examples/heap/list_seq/src/SimplifiedLL.java
  key.ui/examples/heap/vacid0_05_RedBlackTrees/src/vacid0/redblacktree/RedBlackTree.java
  key.ui/examples/heap/vstte12_03_RingBuffer/src/RingBuffer.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/IssueDialog.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/HTMLSyntaxHighlighter.java
  test/Test.java
Labels: JavaJMLParser, :lady_beetle: Bug, Reviewer Feedback

#3385 Introducing a new function symbol seqUpd
  key.core/src/main/antlr4/JmlLexer.g4
  key.core/src/main/java/de/uka/ilkd/key/java/Recoder2KeYConverter.java
  key.core/src/main/java/de/uka/ilkd/key/java/expression/operator/adt/SeqPut.java
  key.core/src/main/java/de/uka/ilkd/key/java/recoderext/adt/SeqPut.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/CreatingASTVisitor.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/JavaASTVisitor.java
  key.core/src/main/java/de/uka/ilkd/key/java/visitor/Visitor.java
  key.core/src/main/java/de/uka/ilkd/key/ldt/SeqLDT.java
  key.core/src/main/java/de/uka/ilkd/key/logic/TermBuilder.java
  key.core/src/main/java/de/uka/ilkd/key/logic/sort/ProgramSVSort.java
  key.core/src/main/java/de/uka/ilkd/key/pp/PrettyPrinter.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/njml/Translator.java
  key.core/src/main/javacc/de/uka/ilkd/key/parser/proofjava/ProofJavaParser.jj
  key.core/src/main/javacc/de/uka/ilkd/key/parser/schemajava/SchemaJavaParser.jj
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/adtProgramDecompositionRules.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/seq.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/seqRules.key
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/ProofCollections.java
  key.core/tacletProofs/seqRules/Taclet_getOfSeqUpd.proof
  key.core/tacletProofs/seqRules/Taclet_lenOfSeqUpd.proof
  key.ui/examples/heap/list_seq/ArrayList.set.key
  key.ui/examples/heap/list_seq/LinkedList.set.key
  key.ui/examples/heap/list_seq/src/ArrayList.java
  key.ui/examples/heap/list_seq/src/LinkedList.java
  key.ui/examples/heap/list_seq/src/List.java
  key.ui/examples/heap/vacid0_05_RedBlackTrees/src/vacid0/redblacktree/AbstractMap.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/sourceview/JavaDocument.java
Labels: Feature, Calculus, Review Request

#3408 Cleanup of declaration of taclet options
  key.core/src/main/java/de/uka/ilkd/key/nparser/builder/DeclarationBuilder.java
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/javaHeader.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/javaRules.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/ldt.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/optionsDeclarations.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/ruleSetsDeclarations.key
Labels: 🛠 Maintenance, RFC
