Repository KeYProject/key, pull requests merged in 2024-06, with the labels that each got.

#3481 Fix loading of taclet proof obligations (issue #3477)
  key.core/src/main/java/de/uka/ilkd/key/taclettranslation/lemma/EmptyEnvInput.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/actions/LemmaGenerationAction.java
Labels: :lady_beetle: Bug, Review Request

#3485 Additional rule for sequences: Swap of sequence is a permutation
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/seqPerm.key
  key.core/tacletProofs/seqPerm/Taclet_seqSwapPreservesSeqPerm.proof
  key.core/tacletProofs/seqPerm/Taclet_seqSwapPreservesSeqPermEQ.proof
Labels: Feature, Calculus

#3431 Hackeython unknown methods
  key.core/src/main/java/de/uka/ilkd/key/proof/init/ProblemInitializer.java
  key.core/src/main/java/de/uka/ilkd/key/settings/ChoiceSettings.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/SLEnvInput.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/SpecExtractor.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/jml/JMLSpecExtractor.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/jml/translation/JMLSpecFactory.java
  key.core/src/main/resources/de/uka/ilkd/key/java/JavaRedux/java/io/PrintStream.java
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/ldt.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/soundDefaultContracts.key
  key.ui/examples/index/default+performance.txt
  key.ui/examples/standard_key/defaultContracts/SimpleMin.java
  key.ui/examples/standard_key/defaultContracts/soundDefault.key
  key.ui/examples/standard_key/defaultContracts/unsoundDefault.key
  key.ui/examples/standard_key/java_dl/java5/for_Iterable.key
  key.ui/examples/standard_key/java_dl/java5/src/For.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/plugins/javac/JavaCompilerCheckFacade.java
Labels: HacKeYthon

#3480 Update Github Action for Gradle
  .github/workflows/code_quality.yml
  .github/workflows/gradle-publish.yml
  .github/workflows/javadoc.yml
  .github/workflows/nightlydeploy.yml
  .github/workflows/opttest.yml
  .github/workflows/tests.yml
  .github/workflows/tests_winmac.yml
Labels: Infrastructure, Review Request, 🛠 Maintenance

#3353 Fix overflow checking
  key.core/src/main/java/de/uka/ilkd/key/nparser/builder/TacletPBuilder.java
  key.core/src/main/java/de/uka/ilkd/key/rule/tacletbuilder/TacletGenerator.java
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/intRulesJavaSemantics.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/intRulesUncheckedSemantics.key
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/integerAssignment2UpdateRules.key
  key.core/src/test/java/de/uka/ilkd/key/nparser/TestTacletEquality.java
  key.core/src/test/resources/de/uka/ilkd/key/nparser/taclets.old.txt
Labels: Documentation, :lady_beetle: Bug, Prover Core, P:HIGH, Calculus, ✋ Soundness

#3484 Fixed operator replacements in WD taclets after changes in PR #3436
  key.core/src/main/java/de/uka/ilkd/key/speclang/WellDefinednessCheck.java
  key.core/src/test/resources/de/uka/ilkd/key/nparser/taclets.old.txt
  key.core/tacletProofs/seqPerm/Taclet_seqSwapPreservesSeqPerm.proof
  key.core/tacletProofs/seqPerm/Taclet_seqSwapPreservesSeqPermEQ.proof
Labels: Review Request

#3490 Overflow follow up fix
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/integerAssignment2UpdateRules.key
  key.core/src/test/java/de/uka/ilkd/key/rule/IntSemanticsTest.java
  key.core/src/test/resources/de/uka/ilkd/key/nparser/taclets.old.txt
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/checkedOF/IntSemanticsCheckedOF.java
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/checkedOF/mOFCheck.proof
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/checkedOF/mOFCheckWrong.key
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/IntSemanticsJava.java
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/intSemanticsJava.key
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/mJava.proof
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/java/mJavaWrong.key
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/IntSemanticsUncheckedOF.java
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/intSemanticsUncheckedOF.key
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/mBigint.proof
  key.core/src/test/resources/de/uka/ilkd/key/rule/intSemantics/uncheckedOF/mBigintWrong.key
Labels: :lady_beetle: Bug, Test cases, Completeness
