Repository KeYProject/key, pull requests merged in 2025-02, with the labels that each got.

#3540 Fix #3452
  key.core/src/main/java/de/uka/ilkd/key/api/ProofManagementApi.java
  key.core/src/main/java/de/uka/ilkd/key/control/KeYEnvironment.java
  key.core/src/main/java/de/uka/ilkd/key/proof/init/AbstractOperationPO.java
  key.core/src/main/java/de/uka/ilkd/key/proof/init/FunctionalOperationContractPO.java
  key.core/src/main/java/de/uka/ilkd/key/rule/tacletbuilder/TacletGenerator.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/njml/Translator.java
  key.core/src/main/java/de/uka/ilkd/key/util/TermUtil.java
  key.core/src/test/java/de/uka/ilkd/key/nparser/Issue3452Test.java
  key.core/src/test/resources/de/uka/ilkd/key/nparser/fix3452/fix/Issue3452Fixture.java
  key.core/src/test/resources/de/uka/ilkd/key/nparser/fix3452/problem/Issue3452IllegalNoState.java
Labels: :lady_beetle: Bug

#3550 Cleanup: Removal of key.api package
  key.core/src/main/java/de/uka/ilkd/key/api/KeYApi.java
  key.core/src/main/java/de/uka/ilkd/key/api/Matcher.java
  key.core/src/main/java/de/uka/ilkd/key/api/ProjectedNode.java
  key.core/src/main/java/de/uka/ilkd/key/api/ProofApi.java
  key.core/src/main/java/de/uka/ilkd/key/api/ProofMacroApi.java
  key.core/src/main/java/de/uka/ilkd/key/api/ProofManagementApi.java
  key.core/src/main/java/de/uka/ilkd/key/api/ProofScriptCommandApi.java
  key.core/src/main/java/de/uka/ilkd/key/api/ProofScriptCommandCall.java
  key.core/src/main/java/de/uka/ilkd/key/api/ScriptApi.java
  key.core/src/main/java/de/uka/ilkd/key/api/ScriptResult.java
  key.core/src/main/java/de/uka/ilkd/key/api/ScriptResults.java
  key.core/src/main/java/de/uka/ilkd/key/api/SearchNode.java
  key.core/src/main/java/de/uka/ilkd/key/api/VariableAssignments.java
  key.core/src/main/java/de/uka/ilkd/key/api/package-info.java
  key.core/src/test/java/de/uka/ilkd/key/rule/IntSemanticsTest.java
  key.core/src/test/java/de/uka/ilkd/key/speclang/njml/ContractLoadingTests.java
Labels: 🛠 Maintenance

#3559 Fix line number alignment in SMT interface
  key.ui/src/main/java/de/uka/ilkd/key/gui/smt/InformationWindow.java
Labels: GUI, HacKeYthon

#3543 Adding a rule for exactInstance of final types. (fixes #3389)
  key.core/src/main/antlr4/KeYLexer.g4
  key.core/src/main/antlr4/KeYParser.g4
  key.core/src/main/java/de/uka/ilkd/key/nparser/varexp/TacletBuilderManipulators.java
  key.core/src/main/java/de/uka/ilkd/key/rule/conditions/FinalTypeVarCond.java
  key.core/src/main/resources/de/uka/ilkd/key/proof/rules/instanceAllocation.key
  key.core/src/test/java/de/uka/ilkd/key/proof/runallproofs/ProofCollections.java
  key.ui/examples/standard_key/types/Final.java
  key.ui/examples/standard_key/types/finalTypes.key
  key.ui/examples/standard_key/types/finalTypes_unprovable.key
Labels: Review Request

#3573 highlight current line in issue editor pane
  key.ui/src/main/java/de/uka/ilkd/key/gui/actions/EditSourceFileAction.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/utilities/CurrentLineHighlighter.java
Labels: GUI, Feature, Review Request
