Repository KeYProject/key, pull requests merged in 2025-08, with the labels that each got.

#3641 Refactoring context menus of sequent views
  key.core/src/main/java/de/uka/ilkd/key/pp/AbbrevMap.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/actions/useractions/UserAction.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/CurrentGoalViewMenu.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/DefaultBuiltInRuleMenuItem.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/InnerNodeViewListener.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/InnerNodeViewMenu.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/InsertHiddenTacletMenuItem.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/InsertSystemInvariantTacletMenuItem.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/MenuItemForTwoModeRules.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/SequentViewListener.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/nodeviews/SequentViewMenu.java
  key.ui/src/main/java/de/uka/ilkd/key/gui/smt/SMTMenuItem.java
  key.util/src/main/java/org/key_project/util/java/StringUtil.java
Labels: 🛠 Maintenance

#3571 Introducing some structure for model method bodies
  key.core/src/main/antlr4/JmlLexer.g4
  key.core/src/main/antlr4/JmlParser.g4
  key.core/src/main/java/de/uka/ilkd/key/speclang/jml/translation/JMLSpecFactory.java
  key.core/src/main/java/de/uka/ilkd/key/speclang/njml/Translator.java
  key.ui/examples/heap/BoyerMoore/BM(BM__bm((I)).JML normal_behavior operation contract.0.proof
  key.ui/examples/heap/BoyerMoore/BM(BM__count((I,_bigint,_bigint)).JML accessible clause.0.proof
  key.ui/examples/heap/BoyerMoore/BM(BM__count((I,_bigint,_bigint)).JML model_behavior operation contract.0.proof
  key.ui/examples/heap/BoyerMoore/BM(BM__monoLemma((I,int,int)).JML normal_behavior operation contract.0.proof
  key.ui/examples/heap/BoyerMoore/src/BoyerMoore.java
Labels: JML Parser, Feature, Review Request, RFC

#3643 Fix NPE using KeY command line interface caused by Java NIO
  key.ui/src/main/java/de/uka/ilkd/key/util/CommandLine.java
Labels: :lady_beetle: Bug

#3620 Preparation for generalizing rule indexing
  key.core/src/main/java/de/uka/ilkd/key/proof/Goal.java
  key.core/src/main/java/de/uka/ilkd/key/proof/MultiThreadedTacletIndex.java
  key.core/src/main/java/de/uka/ilkd/key/proof/SingleThreadedTacletIndex.java
  key.core/src/main/java/de/uka/ilkd/key/proof/TacletIndex.java
  key.core/src/main/java/de/uka/ilkd/key/rule/EqualityModuloProofIrrelevancy.java
  key.core/src/main/java/de/uka/ilkd/key/rule/NoPosTacletApp.java
  key.core/src/main/java/de/uka/ilkd/key/rule/PosTacletApp.java
  key.core/src/main/java/de/uka/ilkd/key/rule/RewriteTaclet.java
  key.core/src/main/java/de/uka/ilkd/key/rule/TacletApp.java
  key.core/src/main/java/de/uka/ilkd/key/rule/UninstantiatedNoPosTacletApp.java
  key.core/src/main/java/de/uka/ilkd/key/rule/conditions/SimplifyIfThenElseUpdateCondition.java
  key.core/src/main/java/de/uka/ilkd/key/rule/inst/SVInstantiations.java
  key.core/src/main/java/de/uka/ilkd/key/rule/label/OriginTermLabelRefactoring.java
  key.core/src/main/java/de/uka/ilkd/key/rule/label/TermLabelRefactoring.java
  key.core/src/main/java/de/uka/ilkd/key/rule/match/vm/VMTacletMatcher.java
  key.core/src/main/java/de/uka/ilkd/key/strategy/AssumesInstantiator.java
  key.core/src/main/java/de/uka/ilkd/key/strategy/BuiltInRuleAppContainer.java
  key.core/src/main/java/de/uka/ilkd/key/strategy/FindTacletAppContainer.java
  key.core/src/main/java/de/uka/ilkd/key/strategy/FocussedRuleApplicationManager.java
  key.ncore.calculus/src/main/java/org/key_project/prover/indexing/FormulaTag.java
  key.ncore.calculus/src/main/java/org/key_project/prover/indexing/FormulaTagManager.java
  key.ncore.calculus/src/main/java/org/key_project/prover/indexing/RuleIndex.java
  key.ncore.calculus/src/main/java/org/key_project/prover/proof/ProofGoal.java
  key.ncore.calculus/src/main/java/org/key_project/prover/rules/RuleApp.java
  key.ncore.calculus/src/main/java/org/key_project/prover/rules/TacletMatcher.java
  key.ncore.calculus/src/main/java/org/key_project/prover/rules/VariableCondition.java
  key.ncore.calculus/src/main/java/org/key_project/prover/rules/instantiation/AssumesMatchResult.java
  key.ncore.calculus/src/main/java/org/key_project/prover/rules/instantiation/SVInstantiations.java
  key.ncore.calculus/src/main/java/org/key_project/prover/sequent/SequentChangeInfo.java
  keyext.exploration/src/main/java/org/key_project/exploration/ProofExplorationService.java
Labels: Review Request, 🛠 Maintenance
